version: "3.8"

services:
  web:
    build: .
    container_name: portfolio

    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py create_superuser_if_needed &&
      python manage.py runserver 0.0.0.0:8000
      "

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    environment:
      DEBUG: "False"

    restart: unless-stopped
