# Generated by Django 5.2.13 on 2026-06-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0002_portfolioprofile_experience_certification_profiletag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioprofile',
            name='primary_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/images/'),
        ),
        migrations.AlterField(
            model_name='portfolioprofile',
            name='resume_pdf',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/resumes/'),
        ),
        migrations.AlterField(
            model_name='portfolioprofile',
            name='secondary_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/images/'),
        ),
    ]
