# Generated by Django 5.2.13 on 2026-06-27 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0004_seed_portfolio_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioprofile',
            name='secondary_image',
        ),
    ]
